version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_install:
      - sphinx-apidoc -o docs/apidoc --private --module-first miranda
    pre_build:
      - git clone https://github.com/ES-DOC/pyessv-archive.git ~/.esdoc/pyessv-archive

conda:
  environment: environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

formats:
  - htmlzip
  - pdf
