envlist = [
  "lint",
  {product = [{prefix = "py3.", start = 10, stop = 14}]},
  "docs"
]
skip_missing_interpreters = true

[env.docs]
description = "Build the documentation with makefile under {basepython}"
labels = ["docs"]
dependency_groups = ["docs"]
commands = [
  ["mkdir", "{envtmpdir}/.esdoc"],
  ["git", "clone", "https://github.com/ES-DOC/pyessv-archive.git", "{envtmpdir}/.esdoc/pyessv-archive"],
  ["make", "build-docs"]
]
commands_post = []
allowlist_externals = ["git", "make", "mkdir"]

[env.extras]
description = "Run tests with extras under {basepython}"
extras = ["extras"]

[env.lint]
description = "Run code quality compliance tests under {basepython}"
labels = ["lint"]
skip_install = true
dependency_groups = ["lint"]
commands_pre = []
commands = [
  ["make", "lint"]
]
commands_post = []
allowlist_externals = ["make"]

[env_run_base]
description = "Run tests with pytest under {basepython}"
setenv = {HOME = "{envtmpdir}", PYTEST_ADDOPTS = "--color=yes --numprocesses=logical --durations=10 --cov=miranda --cov-report=lcov", PYTHONPATH = "{toxinidir}"}
passenv = ["CI", "GITHUB_*", "MIRANDA_*", "READTHEDOCS"]
extras = ["gis", "remote"]
download = true
dependency_groups = ["test"]
install_command = ["python", "-m", "pip", "install", "--no-user", "{opts}", "{packages}"]
commands_pre = [
  ["python", "-m", "pip", "install", "--no-user", "--upgrade", "--no-deps", "--force-reinstall", "--no-binary", "h5py", "h5py>=3.12.1"],
  ["pip", "list"],
  ["pip", "check"]
]
commands = [
  ["mkdir", "{envtmpdir}/.esdoc"],
  ["git", "clone", "https://github.com/ES-DOC/pyessv-archive.git", "{envtmpdir}/.esdoc/pyessv-archive"],
  ["pytest", "{posargs}"]
]
commands_post = [
  ["coverage", "report"]
]
allowlist_externals = ["git", "mkdir"]

[gh.python]
"3.10" = ["py3.10"]
"3.11" = ["py3.11"]
"3.12" = ["py3.12"]
"3.13" = ["py3.13"]
"3.14" = ["py3.14"]
