name: "Bump Patch Version"

on:
  push:
    branches:
      - main
    paths-ignore:
      - HISTORY.rst
      - setup.cfg
      - setup.py
      - tox.ini
      - miranda/__init__.py
      - .github/**.yml
      - .pre-commit-config.yaml

jobs:
  bump_patch_version:
    runs-on: ubuntu-latest
    name: Bump patch version
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Config Commit Bot
        run: |
          git config --local user.email "bumpversion[bot]@ouranos.ca"
          git config --local user.name "bumpversion[bot]"
      - name: Current Version
        run: echo "current_version=$(grep -E '__version__'  miranda/__init__.py | cut -d ' ' -f3)"
      - name: Bump Patch Version
        run: |
          pip install bump2version
          bump2version patch
          echo "new_version=$(grep -E '__version__'  miranda/__init__.py | cut -d ' ' -f3)"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          force: false
          github_token: ${{ secrets.BUMPVERSION_TOKEN }}
          branch: ${{ github.ref }}
